name: tetris
description: A new Flutter project.
publish_to: "none"
version: 2.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  overlay_support: ^2.1.0
  soundpool: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/material.png
    - assets/audios/
    - assets/alipay.jpg
    - assets/wechat.png
flutter_intl:
  enabled: true
